name: Audit and lint
description: Runs Credo, Sobelow,, deps.audit, Doctor
inputs:
  elixir-version:
    required: true
    description: Elixir version to set up
  otp-version:
    required: true
    description: OTP version to set up
  ssh-key:
    description: SSH key to use for the CI
    required: true
  service_name:
    description: 'Name of the service'
    required: true
  #################################################################
  # Everything below this line is optional.
  #################################################################
  check-format:
    description: "Run format check"
    default: 'true'
    required: false
  check-credo:
    description: "Run credo"
    default: 'true'
    required: false
  check-sobelow:
    description: "Run sobelow"
    default: 'true'
    required: false
  check-deps-audit:
    description: "Run deps.audit"
    default: 'true'
    required: false
  check-doc-coverage:
    description: "Run doc coverage"
    default: 'true'
    required: false
  check-xref-graph:
    description: "Run xref graph"
    default: 'true'
    required: false
  xref-graph-fail-above:
    description: "Fail if xref graph has more than this number of warnings"
    default: '0'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Elixir Project
      uses: myriad-actions/elixir-setup@v1
      with:
        elixir-version: ${{ inputs.elixir-version }}
        otp-version: ${{ inputs.otp-version }}
        ssh-key: ${{ inputs.ssh-key }}
      env:
        MIX_ENV: dev

    - name: Check format
      run: mix format --check-formatted
      shell: sh
      if: inputs.check-format == 'true'
    
    - name: Run credo
      run: mix credo
      shell: sh
      if: inputs.check-credo == 'true'

    - name: Run security scan on code
      run: mix sobelow --config
      shell: sh
      if: inputs.check-sobelow == 'true'

    - name: Run audit of dependencies
      run: mix deps.audit
      shell: sh
      if: inputs.check-deps-audit == 'true'

    - name: Run doc coverage
      run: mix doctor
      shell: sh
      if: inputs.check-doc-coverage == 'true'

    - name: Run xref graph
      run: mix xref graph --label compile-connected --fail-above ${{ inputs.xref-graph-fail-above }}
      shell: sh
      if: inputs.check-xref-graph == 'true'
  
    - name: collect and send data to db 
      uses: myriad-actions/security-dashboard-action
      with:
        service_name: ${{ inputs.service_name }}
       
